# Generated by Django 6.0 on 2026-01-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address_user_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='events',
            field=models.JSONField(default=dict, help_text='Event triggers (dict of event flags or list of event names)'),
        ),
    ]
