# Generated by Django 6.0 on 2026-01-23 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teammember_use_custom_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('signup', 'Signup')], db_index=True, default='signup', max_length=32)),
                ('documents', models.JSONField(blank=True, default=dict, help_text='Mapping of document name to version, e.g. {"terms":"2026-01-23"}')),
                ('accepted', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_acceptances',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'event', 'accepted_at'], name='legal_accep_user_id_a5e526_idx')],
            },
        ),
    ]
