# Generated by Django 6.0 on 2026-02-03 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_legalacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('password_hash', models.CharField(max_length=256)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('code_hash', models.CharField(max_length=256)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_signups',
                'indexes': [models.Index(fields=['email', 'created_at'], name='pending_sig_email_948806_idx'), models.Index(fields=['phone', 'created_at'], name='pending_sig_phone_79a057_idx'), models.Index(fields=['expires_at'], name='pending_sig_expires_e86736_idx')],
            },
        ),
    ]
