# Generated by Django 6.0 on 2026-01-11 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_plan_allowed_scan_types_remove_plan_limits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Legal company name', max_length=200)),
                ('vat_number', models.CharField(blank=True, help_text='VAT/ДДС number', max_length=50)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number (ЕИК/БУЛСТАТ)', max_length=50)),
                ('billing_address', models.TextField(help_text='Street address')),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_country', models.CharField(default='Bulgaria', max_length=100)),
                ('billing_zip', models.CharField(blank=True, max_length=20)),
                ('billing_email', models.EmailField(help_text='Email for invoices', max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=50)),
                ('accounting_contact_name', models.CharField(blank=True, help_text='Name of accounting person', max_length=200)),
                ('accounting_contact_email', models.EmailField(blank=True, help_text='Separate accounting email', max_length=254)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15 days'), ('net_30', 'Net 30 days'), ('net_60', 'Net 60 days'), ('prepaid', 'Prepaid')], default='net_30', max_length=20)),
                ('invoice_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('custom_monthly_price', models.DecimalField(decimal_places=2, default=299.0, help_text='Custom negotiated price per month', max_digits=10)),
                ('po_number_required', models.BooleanField(default=False, help_text='Require Purchase Order number')),
                ('custom_invoice_notes', models.TextField(blank=True, help_text='Custom notes to include in all invoices')),
                ('use_stripe', models.BooleanField(default=False, help_text='True = Stripe auto-billing, False = manual invoicing')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usage.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enterprise Customer',
                'verbose_name_plural': 'Enterprise Customers',
                'db_table': 'enterprise_customers',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='e.g., INV-2025-001', max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('period_start', models.DateField(help_text='Billing period start')),
                ('period_end', models.DateField(help_text='Billing period end')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Amount before tax', max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='VAT percentage', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated VAT amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total with VAT', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated invoice PDF', upload_to='invoices/%Y/%m/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='e.g., Bank Transfer, Stripe', max_length=50)),
                ('po_number', models.CharField(blank=True, help_text='Purchase Order number', max_length=100, verbose_name='PO Number')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='usage.enterprisecustomer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usage.subscription')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['enterprise_customer', 'status'], name='invoices_enterpr_4ba787_idx'), models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx')],
            },
        ),
    ]
