# Generated by Django 6.0 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_enterprisecustomer_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, help_text='Stripe Price ID (monthly)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, help_text='Stripe Price ID (yearly)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Legacy Stripe Price ID (monthly). Prefer stripe_price_id_monthly/stripe_price_id_yearly.', max_length=100, null=True),
        ),
    ]
