# Generated by Django 6.0 on 2026-01-31 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_alter_scancategory_name'),
        ('subscriptions', '0009_plandetectoroverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanScanCategoryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plan_scan_category_overrides',
            },
        ),
        migrations.AlterUniqueTogether(
            name='plandetectoroverride',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='plandetectoroverride',
            name='plan_detect_plan_id_b4cfd9_idx',
        ),
        migrations.AddField(
            model_name='plan',
            name='price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price in USD (optional; shown when yearly billing is selected)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planscancategoryoverride',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_overrides', to='scans.scancategory'),
        ),
        migrations.AddField(
            model_name='planscancategoryoverride',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_category_overrides', to='usage.plan'),
        ),
        migrations.RemoveField(
            model_name='plandetectoroverride',
            name='detector',
        ),
        migrations.RemoveField(
            model_name='plandetectoroverride',
            name='plan',
        ),
        migrations.AddIndex(
            model_name='planscancategoryoverride',
            index=models.Index(fields=['plan', 'category'], name='plan_scan_c_plan_id_998b63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planscancategoryoverride',
            unique_together={('plan', 'category')},
        ),
        migrations.DeleteModel(
            name='PlanDetectorOverride',
        ),
    ]
