"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta
from urllib.parse import urlparse

try:
    from dotenv import load_dotenv
    _DOTENV_AVAILABLE = True
except ModuleNotFoundError:
    _DOTENV_AVAILABLE = False
    # `python-dotenv` is convenient for local development, but production
    # deployments often rely on real environment variables.

    def load_dotenv(*args, **kwargs):  # type: ignore[no-redef]
        return False
from django.core.exceptions import ImproperlyConfigured

# Load environment variables
#
# Docker Compose uses a `.env` file for variable substitution by default.
# To avoid host-specific values leaking into containers, local developer overrides
# (like SUBFINDER_BIN/AMASS_BIN) should go into `.env.local`.
base_env = os.path.join(Path(__file__).resolve().parent.parent, '.env')
local_env = os.path.join(Path(__file__).resolve().parent.parent, '.env.local')

# If a developer is relying on `.env` files, make missing python-dotenv a hard
# error to avoid confusing "it runs but ignores my config" situations.
_pre_debug = str(os.getenv('DEBUG', '')).strip().lower() in ('1', 'true', 'yes', 'on')
_pre_running_tests = bool(os.getenv('PYTEST_CURRENT_TEST')) or ('pytest' in sys.modules)
if not _DOTENV_AVAILABLE and (_pre_debug or _pre_running_tests):
    if os.path.exists(base_env) or os.path.exists(local_env):
        raise ImproperlyConfigured(
            'python-dotenv is required to load .env files, but it is not installed. '
            'Install it (pip install python-dotenv) or remove .env usage and set real environment variables.'
        )

load_dotenv(base_env, override=True)
if os.path.exists(local_env):
    load_dotenv(local_env, override=True)

BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    """Parse boolean environment variables.

    Accepts: 1/0, true/false, yes/no, on/off (case-insensitive).
    """

    value = os.getenv(name)
    if value is None:
        return bool(default)
    return str(value).strip().lower() in ('1', 'true', 'yes', 'on')


def _is_running_tests() -> bool:
    """Best-effort detection for test runs.

    CI often runs with `DEBUG=False` even for unit tests. We still want strict
    production validations, but they should not block `manage.py test` or
    pytest runs.
    """

    if os.getenv('PYTEST_CURRENT_TEST'):
        return True
    if 'pytest' in sys.modules:
        return True
    argv = [a.lower() for a in sys.argv if isinstance(a, str)]
    return 'test' in argv or 'pytest' in argv


RUNNING_TESTS = _is_running_tests()

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-2ooh6&ub7ohd-6j&#+4a#bd3^+h=l^mpenwml=alf0@3vzyo8q')
DEBUG = _env_bool('DEBUG', default=False)

# Phone verification fallback
#
# Some environments run with DEBUG=False even for local/staging. When Twilio is
# not configured, you can enable a development fallback (log/email) explicitly.
_phone_fallback_env = os.getenv('PHONE_VERIFICATION_FALLBACK_ENABLED')
if _phone_fallback_env is None:
    PHONE_VERIFICATION_FALLBACK_ENABLED = bool(DEBUG or RUNNING_TESTS)
else:
    PHONE_VERIFICATION_FALLBACK_ENABLED = _env_bool('PHONE_VERIFICATION_FALLBACK_ENABLED', default=False)

# CAPTCHA (Cloudflare Turnstile)
#
# Turnstile works without using Cloudflare as your CDN/DNS. You only need to
# register the site and set the env vars. Validation MUST happen server-side.
TURNSTILE_ENABLED = _env_bool('TURNSTILE_ENABLED', default=False)
TURNSTILE_SECRET_KEY = str(os.getenv('TURNSTILE_SECRET_KEY', '') or '').strip()
TURNSTILE_VERIFY_URL = str(
    os.getenv('TURNSTILE_VERIFY_URL', 'https://challenges.cloudflare.com/turnstile/v0/siteverify')
).strip()
TURNSTILE_TIMEOUT_SECONDS = float(os.getenv('TURNSTILE_TIMEOUT_SECONDS', '3.0'))

# Guard: treat it as enabled only when secret key exists.
if TURNSTILE_ENABLED and not TURNSTILE_SECRET_KEY:
    TURNSTILE_ENABLED = False

# Product mode flags
ACCESS_CONTROLS_ENABLED = _env_bool('ACCESS_CONTROLS_ENABLED', default=False)
SMS_VERIFICATION_ENABLED = _env_bool('SMS_VERIFICATION_ENABLED', default=True)
ENTERPRISE_VERIFICATION_ENABLED = _env_bool('ENTERPRISE_VERIFICATION_ENABLED', default=False)
IPWHOIS_SECURITY_ENABLED = _env_bool('IPWHOIS_SECURITY_ENABLED', default=False)

# Dangerous tools policy: require an authenticated + email-verified user.
DANGEROUS_TOOLS_REQUIRE_EMAIL_VERIFICATION = _env_bool(
    'DANGEROUS_TOOLS_REQUIRE_EMAIL_VERIFICATION',
    default=True,
)

# Donations (frontend can also use REACT_APP_DONATE_URL)
DONATE_URL = str(os.getenv('DONATE_URL', '') or '').strip()

# Email signup verification (pending account) TTL in seconds
EMAIL_SIGNUP_TOKEN_TTL_SECONDS = int(os.getenv('EMAIL_SIGNUP_TOKEN_TTL_SECONDS', '172800'))

# Logging
LOG_FORMAT = os.getenv('LOG_FORMAT', 'plain').lower()

if not DEBUG:
    # Fail fast in production if still using the default/dev key.
    if SECRET_KEY.startswith(
            'django-insecure-') or SECRET_KEY == 'django-insecure-2ooh6&ub7ohd-6j&#+4a#bd3^+h=l^mpenwml=alf0@3vzyo8q':
        if not RUNNING_TESTS:
            raise ImproperlyConfigured('SECRET_KEY must be set via environment in production')

# ALLOWED_HOSTS
ALLOWED_HOSTS_STR = os.getenv('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]

if not DEBUG and not RUNNING_TESTS and (ALLOWED_HOSTS_STR.strip() == '*' or not ALLOWED_HOSTS):
    raise ImproperlyConfigured('ALLOWED_HOSTS must be explicitly set in production (no "*")')

# CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS_STR = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_STR.split(',') if origin.strip()]

INSTALLED_APPS = [
    'jazzmin',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
    'channels',
    'corsheaders',
    'users',
    'scans',
    'usage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.SecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'config.middleware.DisableCSRFForAPIMiddleware',  # Disable CSRF for /api/ endpoints
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'config.middleware.ActivityAuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Database
# Prefer DATABASE_URL when provided (production), fallback to local SQLite.
_database_url = os.getenv('DATABASE_URL')
if _database_url:
    try:
        import dj_database_url
    except Exception as exc:
        raise ImproperlyConfigured(
            'DATABASE_URL is set but dj-database-url is not installed. '
            'Add dj-database-url to requirements.'
        ) from exc

    DATABASES = {
        'default': dj_database_url.parse(
            _database_url,
            conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '60')),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'bugbounty_arsenal.db',
        }
    }

# Cache configuration for rate limiting
_cache_running_pytest = ('pytest' in sys.modules) or bool(os.getenv('PYTEST_CURRENT_TEST'))
_redis_cache_enabled_env = os.getenv('REDIS_CACHE_ENABLED')
_redis_cache_host = os.getenv('REDIS_HOST')
_redis_cache_port = os.getenv('REDIS_PORT')

if not _cache_running_pytest and (
    (_redis_cache_enabled_env is not None and str(_redis_cache_enabled_env).lower() in ('1', 'true', 'yes', 'on'))
    or (_redis_cache_enabled_env is None and _redis_cache_host and _redis_cache_port)
):
    # Use a shared cache in production so rate limits apply consistently
    # across multiple Gunicorn/Daphne workers and containers.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': f'redis://{_redis_cache_host}:{_redis_cache_port}/1',
            'KEY_PREFIX': os.getenv('CACHE_KEY_PREFIX', 'bugbounty-arsenal'),
            'OPTIONS': {
                'socket_connect_timeout': float(os.getenv('REDIS_SOCKET_CONNECT_TIMEOUT', '1.0')),
                'socket_timeout': float(os.getenv('REDIS_SOCKET_TIMEOUT', '1.0')),
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'bugbounty-arsenal-cache',
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'config.middleware.CsrfExemptSessionAuthentication',  # Session auth without CSRF
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Enable format suffix patterns (default is True)
    'URL_FORMAT_OVERRIDE': 'format',  # Allow both .json and ?format=json
    # Custom exception handler for better error messages
    'EXCEPTION_HANDLER': 'config.exception_handlers.custom_exception_handler',
    # Rate limiting
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # General anonymous rate limit
        'user': '1000/hour',  # Authenticated users
        'login': '10/hour',  # Login attempts - 10 tries per hour (more reasonable)
        'signup': '10/hour',
        'token_refresh': '60/hour',
        'jwt_login': '10/hour',
        'email_verify_request': '10/hour',
        'password_reset_request': '10/hour',
        'email_verify_confirm': '30/hour',
        'password_reset_confirm': '30/hour',
        'logout': '60/hour',

        # Scan abuse controls
        'scan_start': '30/hour',
        'scan_stop': '60/hour',
        'export': '50/hour',

        # Phone/company verification abuse controls
        'phone_verify_send': '3/hour',
        'phone_verify_resend': '3/hour',
        'phone_verify_confirm': '20/hour',

        # Anonymous phone verification during strict signup flow
        'phone_verify_confirm_anon': '20/hour',
        'phone_verify_resend_anon': '3/hour',
        'company_verify': '30/hour',
        'company_search': '60/hour',
    }
}

# Scans
# In production we want scans to start immediately (Celery).
# During pytest runs we disable auto-start to keep API tests fast/deterministic.
_scans_auto_start_env = os.getenv('SCANS_AUTO_START')
_running_pytest = 'pytest' in sys.modules
if _scans_auto_start_env is None and (_running_pytest or os.getenv('PYTEST_CURRENT_TEST')):
    SCANS_AUTO_START = False
else:
    SCANS_AUTO_START = str(_scans_auto_start_env or 'True').lower() in ('1', 'true', 'yes', 'on')

# If the Celery broker is down/misconfigured, allow the API to still accept scans
# by spawning a detached management command that runs the scan synchronously.
_scans_fallback_env = os.getenv('SCANS_FALLBACK_LOCAL_RUNNER')
if _scans_fallback_env is None:
    # Default: enabled in production to avoid 503s when broker is unavailable.
    SCANS_FALLBACK_LOCAL_RUNNER = not DEBUG
else:
    SCANS_FALLBACK_LOCAL_RUNNER = str(_scans_fallback_env).lower() in ('1', 'true', 'yes', 'on')

SIMPLE_JWT = {
    # Access tokens should be short-lived; logout invalidation relies on refresh token blacklisting.
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS
# Dev-friendly defaults; in production prefer explicit allowlist via env.
_cors_allowed_origins_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_allowed_origins_str.split(',') if o.strip()] or [
        os.getenv('FRONTEND_URL', 'https://bugbounty-arsenal.com').rstrip('/'),
    ]

# CSRF settings for API
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG  # Only use secure cookies in production
CSRF_USE_SESSIONS = False

# Security Settings (Production)
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', str(not DEBUG)) == 'True'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', str(not DEBUG)) == 'True'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', str(not DEBUG)) == 'True'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', str(not DEBUG)) == 'True'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'same-origin')

# Clickjacking protection
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY' if not DEBUG else 'SAMEORIGIN')

SPECTACULAR_SETTINGS = {
    'TITLE': 'BugBounty Arsenal API',
    'DESCRIPTION': 'Comprehensive Bug Bounty Security Scanner with automated vulnerability detection',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'SWAGGER_UI_FAVICON_HREF': '/static/favicon.ico',
    'REDOC_DIST': 'SIDECAR',
}

# Redis configuration
# Prefer explicit env vars. Defaults should be sensible for common deployments.
# - Docker Compose typically uses REDIS_HOST=redis, REDIS_PORT=6379
# - Single-host installs typically use 127.0.0.1:6379
_redis_host = os.getenv('REDIS_HOST')
_redis_port = os.getenv('REDIS_PORT')

if not _redis_host:
    # Heuristic defaults:
    # - Docker: compose service name
    # - Jump.BG cPanel: local/private Redis endpoint
    # - Otherwise: localhost
    if os.path.exists('/.dockerenv'):
        _redis_host = 'redis'
    elif os.path.exists('/home/bugbount') or os.path.exists('/home/bugbount/app'):
        _redis_host = '127.0.1.204'
    else:
        _redis_host = '127.0.0.1'
if not _redis_port:
    if os.path.exists('/home/bugbount') or os.path.exists('/home/bugbount/app'):
        _redis_port = '39383'
    else:
        _redis_port = '6379'

# Celery with Redis backend
if _running_pytest or os.getenv('PYTEST_CURRENT_TEST'):
    # Tests should not depend on an external broker.
    CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'memory://')
    CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'cache+memory://')
else:
    CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', f'redis://{_redis_host}:{_redis_port}/0')
    CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', f'redis://{_redis_host}:{_redis_port}/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_IGNORE_RESULT = True
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 3600  # 1 hour max
CELERY_TASK_SOFT_TIME_LIMIT = 3500  # 58 minutes soft limit

# Periodic tasks (celery-beat)
CELERY_BEAT_SCHEDULE = {
    'cleanup-stuck-scans': {
        'task': 'scans.tasks.cleanup_stuck_scans_task',
        'schedule': timedelta(minutes=10),
        'kwargs': {'pending_minutes': 30, 'running_minutes': 120},
    },
    'cleanup-expired-scans': {
        'task': 'scans.tasks.cleanup_expired_scans_task',
        'schedule': timedelta(days=1),
    },
}
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # One task at a time per worker
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100  # Recycle worker after 100 tasks

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Admin panel URL — set ADMIN_URL env var to a secret path, e.g. 'bba-62d9d7badcecb2c41ab7021a'
# /admin/ will return 404 to everyone.
ADMIN_URL = os.getenv('ADMIN_URL', 'bba-62d9d7badcecb2c41ab7021a')


# Structured JSON logging (opt-in)
if LOG_FORMAT == 'json':
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'json': {
                '()': 'utils.json_logging.JsonFormatter',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'json',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
        },
    }

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(_redis_host, int(_redis_port))],
        },
    },
}

SCANNER_DETECTOR_MAPPING = {
    'reconnaissance': [
        'subdomain_takeover_detector',
        'dir_listing_detector',
        'security_headers_detector',
        'secret_detector',
        'reflection_detector',
        'cors_detector',
        'graphql_detector',
        'api_security_detector',
    ],
    'web_security': [
        'xss_pattern_detector',
        'sql_pattern_detector',
        'lfi_detector',
        'open_redirect_detector',
        'csrf_detector',
        'header_injection_detector',
        'command_injection_detector',
        'xxe_detector',
        'ssti_detector',
        'prototype_pollution_detector',
        'nosql_injection_detector',
        'cache_poisoning_detector',
        'idor_detector',
        'auth_bypass_detector',
        'fuzz_detector',
        'file_upload_detector',
    ],
    'api_security': [
        'api_security_detector',
        'graphql_detector',
        'graphql_injection_detector',
        'jwt_detector',
        'jwt_vulnerability_scanner',
        'oauth_detector',
        'cors_detector',
        'rate_limit_bypass_detector',
        'idor_detector',
        'nosql_injection_detector',
    ],
    'mobile': [
        'api_security_detector',
        'jwt_detector',
        'oauth_detector',
        'secret_detector',
        'idor_detector',
        'rate_limit_bypass_detector',
    ],
    'comprehensive': [
        'subdomain_takeover_detector',
        'dir_listing_detector',
        'security_headers_detector',
        'secret_detector',
        'reflection_detector',
        'cors_detector',
        'graphql_detector',
        'api_security_detector',
        'xss_pattern_detector',
        'sql_pattern_detector',
        'lfi_detector',
        'open_redirect_detector',
        'csrf_detector',
        'header_injection_detector',
        'command_injection_detector',
        'xxe_detector',
        'ssti_detector',
        'prototype_pollution_detector',
        'nosql_injection_detector',
        'cache_poisoning_detector',
        'idor_detector',
        'auth_bypass_detector',
        'fuzz_detector',
        'file_upload_detector',
        'ssrf_detector',
        'advanced_ssrf_detector',
        'ssrf_oob_detector',
        'jwt_detector',
        'jwt_vulnerability_scanner',
        'oauth_detector',
        'race_condition_detector',
        'graphql_injection_detector',
        'brute_force_detector',
        'rate_limit_bypass_detector',
        'injector',
        'cve_database_detector',
    ],
}

# Note: mobile placeholders removed to avoid missing modules

# ===========================
# STRIPE PAYMENT SETTINGS
# ===========================
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_...')  # Add webhook secret

# Stripe Price IDs (Live Mode)
# These are not secrets, but keep them configurable so DB seeding can be driven by env.
STRIPE_PRICE_PRO_MONTHLY = os.getenv('STRIPE_PRICE_PRO_MONTHLY', '')
STRIPE_PRICE_PRO_YEARLY = os.getenv('STRIPE_PRICE_PRO_YEARLY', '')
STRIPE_PRICE_ENTERPRISE_MONTHLY = os.getenv('STRIPE_PRICE_ENTERPRISE_MONTHLY', '')
STRIPE_PRICE_ENTERPRISE_YEARLY = os.getenv('STRIPE_PRICE_ENTERPRISE_YEARLY', '')

# Frontend URL for redirects
# In production this must be provided explicitly (otherwise links/redirects can silently point to localhost).
FRONTEND_URL = str(os.getenv('FRONTEND_URL', '') or '').strip()
if not FRONTEND_URL and DEBUG:
    FRONTEND_URL = 'http://localhost:3000'

# ===========================
# LEGAL DOCUMENT VERSIONING
# ===========================
# These versions are recorded at signup to provide an auditable acceptance trail.
# Use a stable identifier (e.g. date or semantic version) and bump when documents change.
LEGAL_DOC_VERSIONS = {
    'terms': os.getenv('LEGAL_TERMS_VERSION', '2026-01-23'),
    'privacy': os.getenv('LEGAL_PRIVACY_VERSION', '2026-01-23'),
    'disclaimer': os.getenv('LEGAL_DISCLAIMER_VERSION', '2026-01-23'),
    'aup': os.getenv('LEGAL_AUP_VERSION', '2026-01-23'),
}

# ===========================
# SCAN CONSENT STATEMENT
# ===========================
# Versioned statement shown before each scan. The backend records this version in ScanAuditLog metadata
# when a scan is created/started so you can demonstrate what was agreed to at the time.
SCAN_CONSENT_VERSION = os.getenv('SCAN_CONSENT_VERSION', '2026-01-23')
SCAN_CONSENT_TEXT = os.getenv(
    'SCAN_CONSENT_TEXT',
    (
        'I confirm I have explicit authorization to scan this target and understand I am responsible for '
        'complying with all applicable laws and program rules.'
    ),
)

# Public contact/support addresses
# Keep these configurable; defaults derive from FRONTEND_URL host.
_frontend_host = urlparse(FRONTEND_URL).hostname or ''
PUBLIC_EMAIL_DOMAIN = os.getenv('PUBLIC_EMAIL_DOMAIN', _frontend_host or 'example.com')

SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL', f'support@{PUBLIC_EMAIL_DOMAIN}')
SALES_EMAIL = os.getenv('SALES_EMAIL', f'sales@{PUBLIC_EMAIL_DOMAIN}')
SECURITY_EMAIL = os.getenv('SECURITY_EMAIL', f'security@{PUBLIC_EMAIL_DOMAIN}')
PRESS_EMAIL = os.getenv('PRESS_EMAIL', f'press@{PUBLIC_EMAIL_DOMAIN}')

# ===========================
# EMAIL (SENDGRID / MAILTRAP)
# ===========================
# SendGrid (optional)
# Get your API key from: https://app.sendgrid.com/settings/api_keys
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '')  # Add your SendGrid API key
SENDGRID_FROM_EMAIL = os.getenv('SENDGRID_FROM_EMAIL', 'noreply@bugbounty-arsenal.com')
SENDGRID_FROM_NAME = os.getenv('SENDGRID_FROM_NAME', 'BugBounty Arsenal')

# Generic SMTP (Gmail, Brevo, Outlook, self-hosted Postfix, etc.)
# Takes priority over Mailtrap-specific variables so that users who configure
# SMTP_HOST don't need to remember the Mailtrap-flavoured names.
SMTP_HOST = os.getenv('SMTP_HOST', '')
SMTP_PORT = int(os.getenv('SMTP_PORT', '587') or '587')
SMTP_USER = os.getenv('SMTP_USER', '') or os.getenv('SMTP_USERNAME', '')
SMTP_PASSWORD = os.getenv('SMTP_PASSWORD', '')
SMTP_USE_TLS = _env_bool('SMTP_USE_TLS', default=True)
SMTP_USE_SSL = _env_bool('SMTP_USE_SSL', default=False)

# Mailtrap (optional — kept for backwards compatibility)
# You can use the MAILTRAP_* variables OR the generic SMTP_* ones above.
MAILTRAP_HOST = os.getenv('MAILTRAP_HOST', '') or os.getenv('MAILTRAP_SMTP_HOST', '')
MAILTRAP_PORT = int(os.getenv('MAILTRAP_PORT', '587') or '587')
MAILTRAP_USER = os.getenv('MAILTRAP_USER', '') or os.getenv('MAILTRAP_USERNAME', '')
MAILTRAP_PASSWORD = os.getenv('MAILTRAP_PASSWORD', '') or os.getenv('MAILTRAP_TOKEN', '')
MAILTRAP_USE_TLS = _env_bool('MAILTRAP_USE_TLS', default=True)
MAILTRAP_USE_SSL = _env_bool('MAILTRAP_USE_SSL', default=False)

EMAIL_FROM_EMAIL = os.getenv('EMAIL_FROM_EMAIL', SENDGRID_FROM_EMAIL)
EMAIL_FROM_NAME = os.getenv('EMAIL_FROM_NAME', SENDGRID_FROM_NAME)

# Resend API key (HTTP API — no SMTP ports needed, works on Hetzner/VPS)
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')

# Django email backend selection (priority order):
# 0) Resend HTTP API (anymail) — no SMTP ports, works on any VPS
# 1) Generic SMTP (SMTP_HOST + SMTP_USER + SMTP_PASSWORD) — Gmail, Brevo, Outlook, etc.
# 2) Mailtrap SMTP (MAILTRAP_HOST + MAILTRAP_USER + MAILTRAP_PASSWORD)
# 3) SendGrid API key
# 4) Console (dev-friendly fallback — prints emails to terminal, nothing is sent)
if RESEND_API_KEY:
    INSTALLED_APPS += ['anymail']
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
    ANYMAIL = {'RESEND_API_KEY': RESEND_API_KEY}
    DEFAULT_FROM_EMAIL = EMAIL_FROM_EMAIL
elif SMTP_HOST and SMTP_USER and SMTP_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = SMTP_HOST
    EMAIL_PORT = SMTP_PORT
    EMAIL_USE_TLS = bool(SMTP_USE_TLS)
    EMAIL_USE_SSL = bool(SMTP_USE_SSL)
    EMAIL_HOST_USER = SMTP_USER
    EMAIL_HOST_PASSWORD = SMTP_PASSWORD
    DEFAULT_FROM_EMAIL = EMAIL_FROM_EMAIL
elif MAILTRAP_HOST and MAILTRAP_USER and MAILTRAP_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = MAILTRAP_HOST
    EMAIL_PORT = MAILTRAP_PORT
    EMAIL_USE_TLS = bool(MAILTRAP_USE_TLS)
    EMAIL_USE_SSL = bool(MAILTRAP_USE_SSL)
    EMAIL_HOST_USER = MAILTRAP_USER
    EMAIL_HOST_PASSWORD = MAILTRAP_PASSWORD
    DEFAULT_FROM_EMAIL = EMAIL_FROM_EMAIL
elif SENDGRID_API_KEY:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'apikey'  # This is always 'apikey' for SendGrid
    EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
    DEFAULT_FROM_EMAIL = EMAIL_FROM_EMAIL
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = EMAIL_FROM_EMAIL

# ===========================
# TWILIO SMS VERIFICATION
# ===========================
# Cost: ~$0.01 per SMS
# Development mode: Set TWILIO_ENABLED=False to use console/email fallback
TWILIO_ENABLED = _env_bool('TWILIO_ENABLED', default=False)
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')  # E.g., +15551234567

# Optional: if SMS fails, attempt voice call delivery (requires voice-capable Twilio number).
TWILIO_VOICE_ENABLED = _env_bool('TWILIO_VOICE_ENABLED', default=False)
TWILIO_VOICE_FROM_NUMBER = os.getenv('TWILIO_VOICE_FROM_NUMBER', '')  # Defaults to TWILIO_PHONE_NUMBER if blank

# ===========================
# OWASP ZAP (Docker-based)
# ===========================
# ZAP is an optional, on-demand component that runs as a separate Docker container.
# Requires Docker to be installed and accessible by the server process.
# Set ZAP_ENABLED=True and supply a random ZAP_API_KEY to activate.
#   Generate a key:  python -c "import secrets; print(secrets.token_hex(16))"
ZAP_ENABLED = _env_bool('ZAP_ENABLED', default=False)
ZAP_API_KEY = os.getenv('ZAP_API_KEY', '')
ZAP_DOCKER_IMAGE = os.getenv('ZAP_DOCKER_IMAGE', 'zaproxy/zap-stable')

# ===========================
# MOBILE APP SCANNER
# ===========================
# Uploaded APK/IPA files are stored temporarily and deleted after analysis.
# Default: <BASE_DIR>/tmp/mobile_uploads/
MOBILE_SCAN_UPLOAD_DIR = os.getenv('MOBILE_SCAN_UPLOAD_DIR', '')
MOBILE_SCAN_MAX_FILE_SIZE_MB = int(os.getenv('MOBILE_SCAN_MAX_FILE_SIZE_MB', '100'))

# ===========================
# OPENCORPORATES API
# ===========================
# Free tier: 500 requests/month
# Paid tier: $99/month for 10,000 requests
# Used for company verification (Enterprise plan only)
OPENCORPORATES_API_KEY = os.getenv('OPENCORPORATES_API_KEY', '')
OPENCORPORATES_ENABLED = bool(OPENCORPORATES_API_KEY)

# ===========================
# JAZZMIN ADMIN UI
# ===========================
JAZZMIN_SETTINGS = {
    "site_title": "BugBounty Arsenal",
    "site_header": "BugBounty Arsenal",
    "site_brand": "BBA Admin",
    "site_logo": None,
    "welcome_sign": "Welcome to BugBounty Arsenal Admin",
    "copyright": "BugBounty Arsenal",
    "search_model": ["users.User", "scans.Scan"],
    "topmenu_links": [
        {"name": "Site", "url": "/", "new_window": True},
        {"name": "API Docs", "url": "/api/schema/swagger-ui/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["users", "scans", "subscriptions"],
    "icons": {
        "auth": "fas fa-users-cog",
        "users.user": "fas fa-user",
        "scans.scan": "fas fa-search",
        "scans.vulnerability": "fas fa-bug",
        "usage.subscription": "fas fa-credit-card",
        "usage.subscriptionplan": "fas fa-list",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "jazzmin/admin_dark_v2.css",
    "custom_js": "jazzmin/force_dark.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
