# Generated by Django 6.0 on 2026-01-31 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_alter_scancategory_name'),
        ('subscriptions', '0008_plan_monthly_yearly_stripe_price_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDetectorOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_overrides', to='scans.detectorconfig')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detector_overrides', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'plan_detector_overrides',
                'indexes': [models.Index(fields=['plan', 'detector'], name='plan_detect_plan_id_b4cfd9_idx')],
                'unique_together': {('plan', 'detector')},
            },
        ),
    ]
