# Generated by Django 6.0 on 2026-01-31

from decimal import Decimal

from django.db import migrations


def forwards(apps, schema_editor):
    Plan = apps.get_model('subscriptions', 'Plan')

    for plan in Plan.objects.all():
        monthly = plan.price

        # Keep free plan consistent.
        if monthly is None:
            continue
        if monthly == 0:
            if plan.price_yearly != 0:
                plan.price_yearly = Decimal('0.00')
                plan.save(update_fields=['price_yearly'])
            continue

        # Two months free => pay for 10 months.
        computed = (monthly * Decimal('10')).quantize(Decimal('0.01'))

        # Only fill when missing.
        if plan.price_yearly is None:
            plan.price_yearly = computed
            plan.save(update_fields=['price_yearly'])


def backwards(apps, schema_editor):
    Plan = apps.get_model('subscriptions', 'Plan')

    # Revert only values that match the computed 10x monthly rule.
    for plan in Plan.objects.all():
        monthly = plan.price
        if monthly is None or monthly == 0 or plan.price_yearly is None:
            continue

        computed = (monthly * Decimal('10')).quantize(Decimal('0.01'))
        if plan.price_yearly == computed:
            plan.price_yearly = None
            plan.save(update_fields=['price_yearly'])


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_planscancategoryoverride_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
