# Generated by Django 6.0 on 2026-01-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_scancategory_scan_selected_detectors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancategory',
            name='name',
            field=models.CharField(choices=[('recon', 'Reconnaissance Scan'), ('web', 'Web Application Scan'), ('api', 'API Security Scan'), ('vuln', 'Vulnerability Scan'), ('mobile', 'Mobile Security Scan')], max_length=50, unique=True),
        ),
    ]
